name: WebStatus

on:
  push:
    paths:
    - 'src/Web/WebStatus/**'
    - '.github/workflows/**'
  pull_request:
    paths:
    - 'src/Web/WebStatus/**'
    - '.github/workflows/**'

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: docker compose
      run: docker-compose build webstatus
